### ISSUE TITLE
API authentication error not properly handled 

### ISSUE THREAD

**Issue by bdo** [dunglas/api-doc-parser#12]
When calling `parseHydraDocumentation` on an API that requires authentication and authentication fails, this leads to the following confusing error:
```
TypeError: Cannot read property 'http://www.w3.org/ns/hydra/core#title' of undefined
    at parseHydraDocumentation.js:137
    at <anonymous>
```

Throwing the original 401 Unauthorised error might be a better choice since it would uncover the underlying issue.

**Comment by dunglas** [comment]
I agree. Would you mind opening a PR?
@mauchede WDYT?

**Comment by mauchede** [comment]
I agree too.

This modification will be useful for  `api-platform/admin`. We will know the reason of the failure: if it is an `401` error, we can redirect to the login page.

**Comment by mauchede** [comment]
@bdo : With the version `0.2.0`, it is now possible to handle error:

```js
parseHydraDocumentation('https://demo.api-platform.com')
    .then(
        ({api}) => {
            // No error: you can use the "Api" instance.
        },
        ({api, response, status}) => {
            // An error occured: you can analyze "status" and "response" and handle the error here.
        },
    );
```

__Note__: In all cases, you retrieve an `Api` instance. So if the error is allowed, you can return the `Api` and continue the process.

@dunglas : IMO, this issue can be closed.
